"""Initial migration

Revision ID: 05498fe7d678
Revises: bdd87cc978b2
Create Date: 2026-04-09 09:07:48.877188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05498fe7d678'
down_revision = 'bdd87cc978b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_tournament', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_league', sa.Boolean(), nullable=True))
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('allow_league')
        batch_op.drop_column('allow_tournament')
        batch_op.drop_column('max_players')

    # ### end Alembic commands ###
